### ISSUE TITLE
Menu Item offset? Deface

### ISSUE THREAD

**Issue by salomoko** [boomerdigital/solidus_user_roles#6]
Is the Roles supposed to be a sub item under users? 

<img width="280" alt="users" src="https://user-images.githubusercontent.com/105071/29307831-9deec4de-8160-11e7-922d-8754bc203814.png">

Seems like its at the root level. Is this a  known issue?

**Comment by VitaliyAdamkov** [comment]
+1

**Comment by memotoro** [comment]
Hello @VitaliyAdamkov

I fixed this issue with this pull request (https://github.com/boomerdigital/solidus_user_roles/pull/8). It was merge into master. Just use master version and should be fine.

Regards

**Comment by VitaliyAdamkov** [comment]
Beg my pardon, but as i can see, this pull request does not fix the 'Menu Item offset' issue..

**Comment by memotoro** [comment]
Hello @VitaliyAdamkov 

What I did was to put a fonts awesome icon that pushes the 'Role' word to the right, it makes it aligned with the rest of the menu elements. However, I have the 'Role' menu as an independent module, not as sub-module of the 'Users' as you pointed out (I'm not sure why, I didn't notice that before). That fix worked for me, but you are right about the offset in the sub-module, it is not fixed yet.

Regards
